x-shared-env: &shared-api-worker-env
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD: difyai123456
  VECTOR_STORE: qdrant
  QDRANT_URL: ${QDRANT_URL:-http://qdrant:6333}
  QDRANT_API_KEY: ${QDRANT_API_KEY:-difyai123456}
  QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT:-20}
  QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED:-false}
  QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT:-6334}
  REDIS_DB: 0
  DB_HOST: db
  DB_PORT: 5432
  DB_USERNAME: postgres
  DB_PASSWORD: difyai123456
  DB_DATABASE: dify
  MIGRATION_ENABLED: "true"
  CONSOLE_API_URL: ${CONSOLE_API_URL:-https://dify.prometheusags.ai/api}
  CONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-https://dify.prometheusags.ai}
  SERVICE_API_URL: ${SERVICE_API_URL:-https://dify.prometheusags.ai/api}
  APP_API_URL: ${APP_API_URL:-https://dify.prometheusags.ai/api}
  APP_WEB_URL: ${APP_WEB_URL:-https://dify.prometheusags.ai}
  FILES_URL: ${FILES_URL:-https://dify.prometheusags.ai}
  OPENDAL_FS_ROOT: ${OPENDAL_FS_ROOT:-storage}
  OPENDAL_SCHEME: ${OPENDAL_SCHEME:-fs}
  CELERY_BROKER_URL: redis://:difyai123456@redis:6379/0
  CELERY_BACKEND: redis
  # Enable at least one authentication method
  ENABLE_EMAIL_PASSWORD_LOGIN: "true"
  ALLOW_REGISTER: "true"
  ALLOW_CREATE_WORKSPACE: "true"
  # Plugin daemon configuration
  PLUGIN_DAEMON_URL: ${PLUGIN_DAEMON_URL:-http://plugin_daemon:5002}
  PLUGIN_DAEMON_PORT: ${PLUGIN_DAEMON_PORT:-5002}
  PLUGIN_DAEMON_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
  PLUGIN_DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
  PLUGIN_DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
  VECTOR_STORE: qdrant
  QDRANT_URL: ${QDRANT_URL:-http://qdrant:6333}
  QDRANT_API_KEY: ${QDRANT_API_KEY:-difyai123456}
  QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT:-20}
  QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED:-false}
  QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT:-6334}

services:
