  web:
    image: dify-web-fixed:latest
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-https://dify.prometheusags.ai/api}
      APP_API_URL: ${APP_API_URL:-https://dify.prometheusags.ai/api}
      MARKETPLACE_API_URL: https://marketplace.dify.ai
    depends_on:
      - api
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dify-web.rule=Host(`dify.prometheusags.ai`)"
      - "traefik.http.routers.dify-web.entrypoints=websecure"
      - "traefik.http.routers.dify-web.tls.certresolver=myresolver"
      - "traefik.http.services.dify-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.dify-explore.rule=Host(`dify.prometheusags.ai`) && PathPrefix(`/explore`)"
      - "traefik.http.routers.dify-explore.entrypoints=websecure"
      - "traefik.http.routers.dify-explore.tls.certresolver=myresolver"
      - "traefik.http.routers.dify-explore.service=dify-web"

