  worker:
    image: langgenius/dify-api:1.3.1
    restart: always
    command: celery -A app.celery worker -P gevent -c 1 --loglevel=INFO
    environment:
      <<: *shared-api-worker-env
      MODE: worker
      # Plugin-specific configuration for worker service
      PLUGIN_MAX_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      INNER_API_KEY_FOR_PLUGIN: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
    depends_on:
